server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: barbershop
    # Database mongoDb
  data:
    mongodb:
      host: localhost
      port: 27017
      database: barbershop

token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351